name = "drgustavomendes"
compatibility_date = "2024-12-20"
account_id = "1a481f7cdb7027c30174a692c89cbda1"
compatibility_flags = ["nodejs_compat"]

# ========== DATABASES ==========
[[d1_databases]]
binding = "DB"
database_name = "drgustavomendes-db"
database_id = "1189d5ea-8769-4d66-adb8-d4cbc04a3af4"

# ========== STORAGE ==========
[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "drgustavomendes-assets"

[[kv_namespaces]]
binding = "SITE_CACHE"
id = "ee0f09bcb97149ecb64f09d4276d0332"

# ========== AI & SEARCH ==========
[ai]
binding = "AI"

# Vectorize para busca semântica (criar depois via CLI)
# [[vectorize]]
# binding = "BLOG_INDEX"
# index_name = "drgustavomendes-blog-search"

# ========== OBSERVABILITY ==========
[observability]
enabled = true
head_sampling_rate = 1

# Analytics Engine (ativar no dashboard)
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# ========== ASYNC PROCESSING ==========
# Queues (criar via CLI: wrangler queues create drgustavomendes-emails)
# [[queues.producers]]
# binding = "EMAIL_QUEUE"
# queue = "drgustavomendes-emails"

# [[queues.consumers]]
# queue = "drgustavomendes-emails"
# max_batch_size = 10
# max_wait_time_ms = 30000

# ========== DURABLE OBJECTS ==========
# [[durable_objects.bindings]]
# name = "CHAT_SESSIONS"
# class_name = "ChatSession"
# script_name = "drgustavomendes"

# [[migrations]]
# tag = "v1"
# new_classes = ["ChatSession"]

# ========== BROWSER RENDERING ==========
# browser = { binding = "BROWSER" }

# ========== ENVIRONMENT ==========
[env.production]
vars = { ENVIRONMENT = "production" }
